failure test

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -7,6 +7,8 @@ jobs:
     steps:
       - name: Step 1
         run: sleep 20
+      - name: Fail
+        run: exit 1 # fail for a change...
       - name: Runs on Failure
         if: failure()
         run: echo "Runs only on failure"
